version: '3.8'

services:
  database:
    container_name: mariadb
    image: mariadb:10
    ports:
      - ${DATABASE_PORT}:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASS}
    restart: on-failure