version: '3.8'

services:
  proxy:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./.infra/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nest_backend
      - go_backend
    networks:
      - backend

  database:
    container_name: mariadb
    image: mariadb:10
    ports:
      - ${DATABASE_PORT}:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    networks:
      - backend
    restart: unless-stopped
    volumes:
      - ./.infra/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql

  nest_backend:
    container_name: nestjs_backend
    build:
      context: ./nestjs_backend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - 3333:3333
    env_file:
      - ./nestjs_backend/.env
    environment:
      DATABASE_URL: mysql://${DATABASE_USER}:${DATABASE_PASS}@database:${DATABASE_PORT}/${DATABASE_NAME}
    networks:
      - backend
    command: ["npm", "run", "start:prod"]

  go_backend:
    container_name: go_backend
    build:
      context: ./go_backend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - 3334:3334
    env_file:
      - ./go_backend/.env
    environment:
      DATABASE_URL: ${DATABASE_USER}:${DATABASE_PASS}@tcp(database:${DATABASE_PORT})/${DATABASE_NAME}?parseTime=true
    networks:
      - backend

networks:
  backend:
    driver: bridge
