version: '3.8'

services:
  database:
    container_name: mariadb
    image: mariadb:10
    ports:
      - ${DATABASE_PORT}:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    networks:
      - backend
    restart: unless-stopped

  backend:
    container_name: nestjs_backend
    build:
      context: ./nestjs_backend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - 3333:3333
    env_file:
      - ./nestjs_backend/.env
    environment:
      DATABASE_URL: mysql://${DATABASE_USER}:${DATABASE_PASS}@database:${DATABASE_PORT}/${DATABASE_NAME}
    networks:
      - backend

networks:
  backend:
    driver: bridge
